"""Historical-only wastage risk scoring for upcoming item/location periods."""

from __future__ import annotations

from pyspark.sql import DataFrame, functions as F


def build_wastage_risk(
    tables: dict[str, DataFrame], menu_features: DataFrame, horizon_days: int = 30,
    model_predictions: DataFrame | None = None,
) -> DataFrame:
    """Rank item/location pairs and optionally attach persisted model inference.

    The historical rate remains an auditable explanatory feature. Production
    demand-planning builds pass ``model_predictions`` generated by the
    persisted supervised wastage model; compact analytical fixtures may omit
    it and continue to exercise the historical score contract.
    """
    if horizon_days < 1 or horizon_days > 366:
        raise ValueError("horizon_days must be between 1 and 366")
    historical = tables["wastage"].groupBy("Item_ID", "Location_ID").agg(
        F.sum("Quantity_Wasted").alias("historical_quantity_wasted"),
        F.sum("Preparation_Quantity").alias("historical_preparation_quantity"),
        F.sum("Total_Wastage_Cost").alias("historical_wastage_cost"),
        F.countDistinct("Wastage_Date").alias("observed_days"),
        F.max("Wastage_Date").alias("latest_wastage_date"),
    ).withColumn(
        "historical_wastage_percentage",
        F.when(F.col("historical_preparation_quantity") > 0,
               F.col("historical_quantity_wasted") / F.col("historical_preparation_quantity") * 100.0),
    )
    popularity = menu_features.select("Item_ID", "item_popularity").dropDuplicates(["Item_ID"])
    scored = historical.join(popularity, "Item_ID", "left").withColumn(
        "risk_score", F.col("historical_wastage_percentage")
    )
    threshold = scored.approxQuantile("risk_score", [0.75], 0.01)
    cutoff = float(threshold[0]) if threshold else 0.0
    result = scored.withColumn("historical_high_wastage_risk", F.coalesce(F.col("risk_score") >= F.lit(cutoff), F.lit(False))).withColumn(
        "risk_cutoff_percentile", F.lit(75.0)
    ).withColumn("risk_cutoff_value", F.lit(cutoff)).withColumn(
        "prediction_period_start", F.date_add(F.to_date("latest_wastage_date"), 1)
    ).withColumn(
        "prediction_period_end", F.date_add(F.to_date("latest_wastage_date"), horizon_days)
    ).withColumn("forecast_horizon_days", F.lit(horizon_days)).withColumn(
        "risk_method", F.lit("Historical wastage-rate 75th percentile explanatory score")
    )
    if model_predictions is None:
        return result.withColumn("high_wastage_risk", F.col("historical_high_wastage_risk"))
    required = set(("Item_ID", "Location_ID", "model_risk_probability", "model_high_wastage_risk", "model_version"))
    missing = sorted(required - set(model_predictions.columns))
    if missing:
        raise ValueError(f"wastage model predictions missing columns: {missing}")
    model_columns = [
        name for name in model_predictions.columns
        if name.startswith("model_feature_")
    ]
    return result.withColumn(
        "risk_method", F.lit("Persisted supervised wastage-risk model with historical-rate evidence")
    ).join(
        model_predictions.select(
            "Item_ID", "Location_ID", "model_risk_probability", "model_high_wastage_risk", "model_version",
            *model_columns,
        ).dropDuplicates(["Item_ID", "Location_ID"]),
        ["Item_ID", "Location_ID"], "left",
    ).withColumn(
        "high_wastage_risk", F.coalesce(F.col("model_high_wastage_risk"), F.col("historical_high_wastage_risk"))
    )
